// Base de receitas de exito/sucumbencia - gerado da base auditada do EasyJur
const DADOS = [
{
"id": 2613231,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 100000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "1/2",
"nf": "",
"situacao_atual": "Correto, são contratos diferentes",
"resolucao_yasmin_kim": "Correto, são contratos diferentes",
"alerta": "",
"a_definir": false
},
{
"id": 5055458,
"cliente": "Edilson Binotto",
"tipo": "Êxito",
"via": "Judicial",
"valor": 50000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "0000435-29.2008.4.01.4300",
"parcela": "2/2",
"nf": "",
"situacao_atual": "Gilmar de Lima; exito a pagar 06/2026 e 07/2026; lancado 100%",
"resolucao_yasmin_kim": "Correto, são contratos diferentes",
"alerta": "",
"a_definir": false
},
{
"id": 3507698,
"cliente": "José Leonel Martins Filho",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 5000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Jose Leonel; exito acordo; VERIFICAR COM DR WILLIAN QUANTAS PARCELAS SAO (indefinido)",
"resolucao_yasmin_kim": "CORRETO, saldo remanescente",
"alerta": "",
"a_definir": false
},
{
"id": 2611353,
"cliente": "Inoven Comércio Internacional",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 213.74,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "1/1 (1 de 10 do acordo)",
"nf": "",
"situacao_atual": "Confissao de divida L S Ferreira; honor 10% (10x R$213,74), 1a em 15/09/2022",
"resolucao_yasmin_kim": "CORRETO, Êxito parcelado em 10x, cliente não pagou 4 parcelas",
"alerta": "",
"a_definir": false
},
{
"id": 2611354,
"cliente": "Inoven Comércio Internacional",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 213.74,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "parc acordo",
"nf": "",
"situacao_atual": "Confissao de divida L S Ferreira; honor 10% (10x R$213,74)",
"resolucao_yasmin_kim": "CORRETO, Êxito parcelado em 10x, cliente não pagou 4 parcelas",
"alerta": "",
"a_definir": false
},
{
"id": 2611355,
"cliente": "Inoven Comércio Internacional",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 213.74,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "parc acordo",
"nf": "",
"situacao_atual": "Confissao de divida L S Ferreira; honor 10% (10x R$213,74)",
"resolucao_yasmin_kim": "CORRETO, Êxito parcelado em 10x, cliente não pagou 4 parcelas",
"alerta": "",
"a_definir": false
},
{
"id": 2611356,
"cliente": "Inoven Comércio Internacional",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 213.74,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "parc acordo",
"nf": "",
"situacao_atual": "Confissao de divida L S Ferreira; honor 10% (10x R$213,74); faturado=true",
"resolucao_yasmin_kim": "CORRETO, Êxito parcelado em 10x, cliente não pagou 4 parcelas",
"alerta": "",
"a_definir": false
},
{
"id": 3191849,
"cliente": "Compass Comércio (Vetor)",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 110.4,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "4/5",
"nf": "6088 parcial",
"situacao_atual": "Acordo extrajudicial Compass x Murilo Moritz; repasse 110,40",
"resolucao_yasmin_kim": "CORRETO, Êxito parcelado em 5x, cliente não pagou 2 parcelas",
"alerta": "",
"a_definir": false
},
{
"id": 3191850,
"cliente": "Compass Comércio (Vetor)",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 110.4,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "5/5",
"nf": "6088 complemento",
"situacao_atual": "Acordo extrajudicial Compass x Murilo Moritz; repasse 110,40",
"resolucao_yasmin_kim": "CORRETO, Êxito parcelado em 5x, cliente não pagou 2 parcelas",
"alerta": "",
"a_definir": false
},
{
"id": 5038069,
"cliente": "Valdemir de Souza Messias",
"tipo": "Sucumbência",
"via": "Judicial",
"valor": 122205.93,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Nao cobrar: acerto Floripa, ver com a Mariana",
"processo": "5004815-17.2026.8.24.0125",
"parcela": "",
"nf": "",
"situacao_atual": "Valdemir; sucumbencia; status ABERTO/VENCIDO no sistema (nao ha baixa lancada); observacao diz 'ja pago, so baixar' mas NAO cobrar; ver acerto FLN com Mari e baixa com Dr. Kim",
"resolucao_yasmin_kim": "Mantido esse  e excluido id duplicado | CONTROLADORIA: consta pago na observacao mas no sistema esta ABERTO/VENCIDO; nao cobrar; ver acerto FLN com Mari e forma de baixa com Dr. Kim",
"alerta": "",
"a_definir": false
},
{
"id": 3217818,
"cliente": "Brava Beach Empreendimentos",
"tipo": "Êxito",
"via": "Judicial",
"valor": 81562.91,
"status_sistema": "Cancelado",
"acao": "EXCLUIR/CANCELAR",
"farol": "EXCLUIR",
"proximo_passo": "Confirmar cancelamento/baixa no sistema",
"processo": "5011309-48.2024.8.24.0033",
"parcela": "",
"nf": "",
"situacao_atual": "CANCELADO (status C). Contrato suspenso para virar o do id 3916889 (Brava Beach); exito R$80.000 na hipotese; alinhado Dr Kim 28/09",
"resolucao_yasmin_kim": "Cancelado, pois contrato foi suspenso para virar o contrato do ID 3916889 (que até essa data não saiu)",
"alerta": "",
"a_definir": false
},
{
"id": 3916889,
"cliente": "Brava Beach Empreendimentos",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 80000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Exito R$80.000 na hipotese de exito, corrigido IPCA",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 4014053,
"cliente": "Kalani Empreendimentos",
"tipo": "Êxito",
"via": "Judicial",
"valor": 15000,
"status_sistema": "Cancelado",
"acao": "EXCLUIR/CANCELAR",
"farol": "EXCLUIR",
"proximo_passo": "Confirmar cancelamento/baixa no sistema",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "CANCELADO (status C). Honor sucesso R$15.000 SE acao julgada improcedente (condicional)",
"resolucao_yasmin_kim": "ID CANCELADO, NÃO VIROU AÇÃO JUDICIAL.",
"alerta": "",
"a_definir": false
},
{
"id": 5219361,
"cliente": "J. A. Russi",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 15000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Russi; 5% de exito sobre entrada R$300.000; audio Dr Maiko 24/09, alinhar fluxo com Sr Ricardo; cliente paga a cada 6 meses",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 2456165,
"cliente": "Alcir Marcos Pinto",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 12000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Exito = cancelamento de hipoteca por qualquer meio",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 2723899,
"cliente": "Alcir Marcos Pinto",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 12000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Honor fixo R$12.000 na cessao de quotas Irmaos Pinto",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 4488453,
"cliente": "J. A. Russi",
"tipo": "Êxito",
"via": "Judicial",
"valor": 10000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5010443-72.2025.8.24.0011",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Russi x Altair Marchi; EXITO ATRELADO A REUNIAO COM DR MAIKO 22/01/2026",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 4488456,
"cliente": "J. A. Russi",
"tipo": "Êxito",
"via": "Judicial",
"valor": 10000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5010442-87.2025.8.24.0011",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Russi x Gustavo Gums; EXITO ATRELADO A REUNIAO COM DR MAIKO 21/01/2026",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 3552558,
"cliente": "Célio Pacheco",
"tipo": "Êxito",
"via": "Judicial",
"valor": 4536.79,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5007707-06.2011.4.04.7208",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Celio Pacheco; execucao fiscal; anulacao total divida; 10% de R$45.367,87",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 2192630,
"cliente": "Célio Pacheco",
"tipo": "Sucumbência",
"via": "A definir (standby)",
"valor": 4500,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Sucumbencia Itau (Celio Pacheco); venc 20/04/2020",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 3535152,
"cliente": "Valmir dos Santos",
"tipo": "Êxito",
"via": "Judicial",
"valor": 4070.96,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "0300470-04.2017.8.24.0006",
"parcela": "1/4",
"nf": "",
"situacao_atual": "Valmir; reajuste IGPM; total R$16.283,84 em 4x",
"resolucao_yasmin_kim": "CORRETO - 4 parcelas",
"alerta": "",
"a_definir": false
},
{
"id": 3535165,
"cliente": "Valmir dos Santos",
"tipo": "Êxito",
"via": "Judicial",
"valor": 4070.96,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "0300470-04.2017.8.24.0006",
"parcela": "2/4",
"nf": "",
"situacao_atual": "Valmir; reajuste IGPM; parcela 2/4",
"resolucao_yasmin_kim": "CORRETO - 4 parcelas",
"alerta": "",
"a_definir": false
},
{
"id": 3535166,
"cliente": "Valmir dos Santos",
"tipo": "Êxito",
"via": "Judicial",
"valor": 4070.96,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "0300470-04.2017.8.24.0006",
"parcela": "3/4",
"nf": "",
"situacao_atual": "Valmir; reajuste IGPM; parcela 3/4",
"resolucao_yasmin_kim": "CORRETO - 4 parcelas",
"alerta": "",
"a_definir": false
},
{
"id": 3535167,
"cliente": "Valmir dos Santos",
"tipo": "Êxito",
"via": "Judicial",
"valor": 4070.96,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "0300470-04.2017.8.24.0006",
"parcela": "4/4",
"nf": "",
"situacao_atual": "Valmir (filho Abner); reajuste IGPM; parcela 4/4",
"resolucao_yasmin_kim": "CORRETO - 4 parcelas",
"alerta": "",
"a_definir": false
},
{
"id": 2612171,
"cliente": "Inoven Comércio Internacional",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 110,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "acordo 10%",
"nf": "3884",
"situacao_atual": "Acordo extrajud Inoven x Widerson Santos; parcela R$1.100 x10%",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 2612172,
"cliente": "Inoven Comércio Internacional",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 110,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "acordo 10%",
"nf": "3685",
"situacao_atual": "Acordo extrajud Inoven x Widerson Santos",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 2612173,
"cliente": "Inoven Comércio Internacional",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 110,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "acordo 10%",
"nf": "",
"situacao_atual": "Acordo extrajud Inoven x Widerson Santos",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 2612174,
"cliente": "Inoven Comércio Internacional",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 110,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "acordo 10%",
"nf": "",
"situacao_atual": "Acordo extrajud Inoven x Widerson Santos",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 2612175,
"cliente": "Inoven Comércio Internacional",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 110,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "acordo 10%",
"nf": "",
"situacao_atual": "Acordo extrajud Inoven x Widerson Santos",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 3565433,
"cliente": "Warusky Comércio",
"tipo": "Êxito",
"via": "Judicial",
"valor": 0.1,
"status_sistema": "Aberto",
"acao": "PENDENTE VER MARI/KIM",
"farol": "VERIFICAR",
"proximo_passo": "Definir com Mari / Dr. Kim",
"processo": "5012890-10.2024.4.04.7205",
"parcela": "",
"nf": "",
"situacao_atual": "Warusky; revisao fiscal IRPJ/CSLL; MS com seguranca DENEGADA 01/05/2025 (1a inst); contrato=8%, obs=10%; valor a ratificar Dr Kim",
"resolucao_yasmin_kim": "Contratos diferentes, um mais geral e outro pra irpjj. Preciso ver com Dr Kim",
"alerta": "",
"a_definir": true
},
{
"id": 3578452,
"cliente": "Komlog Importacao (rec. judicial)",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 0.1,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Nao cobrar: alvara saiu, cuidar deposito e verificar com Dr. Kim",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "ATENCAO: status A (nao cancelado). Komeco/Komlog: saiu decisao mandando expedir alvara; colocar no radar; verificar c/ Dr Kim e cuidar deposito. Valor 0,10 placeholder",
"resolucao_yasmin_kim": "ID 3578452 EXCLUIDO, DUPLICADO.",
"alerta": "",
"a_definir": true
},
{
"id": 3989884,
"cliente": "J. A. Russi",
"tipo": "Êxito",
"via": "Judicial",
"valor": 0.1,
"status_sistema": "Aberto",
"acao": "PENDENTE VER MARI/KIM",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Definir com Mari / Dr. Kim",
"processo": "REsp 1384010 (STJ)",
"parcela": "",
"nf": "",
"situacao_atual": "Russi (Antidio Reis); exito 2,5% s/ valor causa, so com transito em julgado; EXITO AINDA NAO SAIU; VER MARI",
"resolucao_yasmin_kim": "VER MARI",
"alerta": "",
"a_definir": true
},
{
"id": 4919802,
"cliente": "Incorporadora Colinas de Camboriú (ABC)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 0.1,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "5004500-25.2026.8.24.0113 (cumpr. sent.) / 5000888-84.2023.8.24.0113",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Colinas ABC x G.A Investimentos (em rec. judicial); ATENCAO: 'nao fui autorizado pelo Dr Maiko', valor 0,10, ainda ver sobre exito",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": true
},
{
"id": 2827056,
"cliente": "Ayrton Justino Silva Jr (Embrainc)",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 150000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Permuta Shopping Andorinha; R$150.000 na assinatura da escritura de permuta; depende da escritura ser assinada",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 3727212,
"cliente": "Célio Pacheco",
"tipo": "Êxito",
"via": "Judicial",
"valor": 101065.16,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "2365941",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Celio Pacheco; exito R$1.010.651,57 x10% = 101.065,16; print anexo no sistema",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 2197338,
"cliente": "José Leonel Martins Filho",
"tipo": "Êxito",
"via": "Judicial",
"valor": 75000,
"status_sistema": "Aberto",
"acao": "PENDENTE VER MARI/KIM",
"farol": "VERIFICAR",
"proximo_passo": "Definir com Mari / Dr. Kim",
"processo": "extrajudicial (aditivo contrato 71499)",
"parcela": "",
"nf": "",
"situacao_atual": "Jose Leonel; honorarios 1o aditivo contrato 17/07/2020 (dissolucao Cota Empreendimentos); VER MARI",
"resolucao_yasmin_kim": "VER MARI",
"alerta": "",
"a_definir": false
},
{
"id": 3691514,
"cliente": "Renatec Quadros Eletricos",
"tipo": "Êxito",
"via": "Judicial",
"valor": 71679.49,
"status_sistema": "Aberto",
"acao": "ACAO JUDICIAL",
"farol": "ACAO JUDICIAL",
"proximo_passo": "Acompanhar a ação de cobrança",
"processo": "0001146-17.2019.5.20.0006",
"parcela": "",
"nf": "",
"situacao_atual": "Reclamatoria trabalhista (Renatec/Roberto Santos); valor acao R$868.799; exito 10%=R$86.879,90 (lancado R$71.679,49); em acao judicial de cobranca",
"resolucao_yasmin_kim": "AÇÃO JUDICIAL COBRANÇA",
"alerta": "",
"a_definir": false
},
{
"id": 4366267,
"cliente": "Marco Aurélio Ambrósio (MG7)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 69238,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "0300072-73.2017.8.24.0033 / AI 5045130-11.2025.8.24.0000",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Jose Caetano Ambrosio x Varella Motos; TRANSITO EM JULGADO 02/12/2025; 10% s/ R$692.380; MADURO",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 3099062,
"cliente": "Moonville Construtora",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 66422.35,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Moonville - multa Ed. Galli; TETO contratual corrigido IGP-M=R$66.422,35; exito=8% do valor reduzido ATE o teto; FALTA apurar reducao obtida p/ confirmar se teto foi atingido; competencia 2027",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 4086352,
"cliente": "Marco Aurélio Ambrósio (MG7)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 65000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "0307222-71.2018.8.24.0033",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Sandra Ambrosio x Banrisul; sentenca improcedente garantiu imovel; exito 10% s/ base sugerida R$650k (conferir contrato); valor estimado",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 3344759,
"cliente": "Alcir Marcos Pinto",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 57823.29,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "so imagem no sistema; precisa verificar objeto no GED do contrato 71703",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 4091349,
"cliente": "Marco Aurélio Ambrósio (MG7)",
"tipo": "Sucumbência",
"via": "Judicial",
"valor": 52481.87,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "0307222-71.2018.8.24.0033",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Sandra Ambrosio x Banrisul; ARQUIVADO DEF. 17/09/2025; TRANSITO EM JULGADO 29/06/2025; 10% s/ R$524.818; MADURO",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 2199600,
"cliente": "J. A. Russi",
"tipo": "Êxito",
"via": "Judicial",
"valor": 50000,
"status_sistema": "Aberto",
"acao": "PENDENTE VER MARI/KIM",
"farol": "VERIFICAR",
"proximo_passo": "Definir com Mari / Dr. Kim",
"processo": "0303009-42.2015.8.24.0125",
"parcela": "",
"nf": "",
"situacao_atual": "Russi; reintegracao de posse; processo ATIVO em fase de instrucao (2o grau); exito R$50.000; VER MARI",
"resolucao_yasmin_kim": "VER MARI",
"alerta": "",
"a_definir": false
},
{
"id": 3170921,
"cliente": "Nilmar Barbieri Junior",
"tipo": "Êxito",
"via": "Judicial",
"valor": 50000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5053708-71.2023.4.04.7000",
"parcela": "7/31",
"nf": "",
"situacao_atual": "Honorarios diversos; parcela 7/31 (total R$310.000)",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 4977121,
"cliente": "Edilson Binotto",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 50000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "extrajudicial / sem processo",
"parcela": "1/1 (50% Silva)",
"nf": "",
"situacao_atual": "Exito R$100.000 (50% Silva=50.000); devido em 10 dias da decisao do TRF1 que revogue tutela do Incra; CONDICIONADO a decisao",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 2507917,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507918,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507919,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507920,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507921,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507923,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507924,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507925,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507926,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507927,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507928,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507929,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507930,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507931,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507932,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507933,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507934,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507935,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 2507936,
"cliente": "Binotto S/A Logística",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "parcela tributario (20x)",
"nf": "",
"situacao_atual": "Binotto S/A; exito tributario R$25.000/parcela (20x, base R$1mi); AGUARDAR conforme orientacao",
"resolucao_yasmin_kim": "CORRETO, AINDA NÃO COBRAR (DR KIM)",
"alerta": "",
"a_definir": false
},
{
"id": 3905760,
"cliente": "Edilson Binotto",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Exito contrato de parceria Jorge Maurique SIA x Silva&Silva; verificar objeto",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 4360887,
"cliente": "Marco Aurélio Ambrósio (MG7)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 25000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5044500-45.2023.4.04.7200",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Marco Aurelio Ambrosio MG7; ARQUIVAMENTO da representacao fiscal penal; exito R$25.000; MADURO",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 3737565,
"cliente": "Grace Bay Residence (Poti)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 19143.55,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5002699-77.2022.8.24.0125 / 0002575-43.2022.8.16.0113",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Acordo Grace Bay Residence x Vanderlei Fiorati; parcela c/ correcao INPC+juros; R$16.017,11 corrigido=R$19.143,55",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 3555984,
"cliente": "Alianca Empreendimentos Imobiliarios (J.A.)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 16700,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "5012332-21.2021.8.24.0005",
"parcela": "",
"nf": "",
"situacao_atual": "Alianca x Camboriu (ISS); precatorio; exito 10%=R$16.700; Dr Kim 28/09 jogar p/ 31/12/26, provavel receber esse ano",
"resolucao_yasmin_kim": "Dr Kim disse que não saiu, jogar para 31/12/26, provável que receberemos ainda esse ano",
"alerta": "",
"a_definir": false
},
{
"id": 2446471,
"cliente": "BHM Têxtil",
"tipo": "Êxito",
"via": "Judicial",
"valor": 16000,
"status_sistema": "Aberto",
"acao": "PENDENTE VER MARI/KIM",
"farol": "VERIFICAR",
"proximo_passo": "Definir com Mari / Dr. Kim",
"processo": "extrajudicial (contrato 71302 assessoria)",
"parcela": "",
"nf": "",
"situacao_atual": "BHM Textil; exito SELIC 10% de R$160.000; contrato assessoria encerrado 16/07/2025; VER MARI",
"resolucao_yasmin_kim": "VER MARI",
"alerta": "",
"a_definir": false
},
{
"id": 2582594,
"cliente": "Péricles Martins Pinto",
"tipo": "Êxito",
"via": "Judicial",
"valor": 15749.61,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "extrajudicial / sem processo",
"parcela": "2/2",
"nf": "",
"situacao_atual": "Acao Stalin Passos; cliente pagou 1a, 2a ficou p/ decisao judicial; Mariana cobrou 30/03/2026, cliente diz que ficou com adv Bertollo, Maiko vai ver; AGUARDAR decisao",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 3201663,
"cliente": "Vilmar Malheiros dos Santos",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 15000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Exito = 30 dias na posse do imovel (imobiliario); venc antigo 05/02/2018",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 3463059,
"cliente": "Embrafrio Armazéns Gerais (AR)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 13931.2,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5142425-81.2022.8.24.0023",
"parcela": "9/12",
"nf": "8317 AUTHORIZED",
"situacao_atual": "Embrafrio; execucao fiscal; extincao parcial divida R$1,67mi; 10% em 12x; NF emitida, parcela 9/12 em aberto",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 3463060,
"cliente": "Embrafrio Armazéns Gerais (AR)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 13931.2,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5142425-81.2022.8.24.0023",
"parcela": "10/12",
"nf": "8510 AUTHORIZED",
"situacao_atual": "Embrafrio; 10% em 12x; NF emitida, parcela 10/12 em aberto",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 3463061,
"cliente": "Embrafrio Armazéns Gerais (AR)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 13931.2,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5142425-81.2022.8.24.0023",
"parcela": "11/12",
"nf": "8676 AUTHORIZED",
"situacao_atual": "Embrafrio; 10% em 12x; NF emitida, parcela 11/12 em aberto",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 3463062,
"cliente": "Embrafrio Armazéns Gerais (AR)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 13931.2,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5142425-81.2022.8.24.0023",
"parcela": "12/12",
"nf": "8859 AUTHORIZED",
"situacao_atual": "Embrafrio; parcela final 12/12; NF emitida mas boleto DELETED",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 2193879,
"cliente": "Roberto Carlos de Souza",
"tipo": "Êxito",
"via": "Judicial",
"valor": 10000,
"status_sistema": "Aberto",
"acao": "PENDENTE VER MARI/KIM",
"farol": "VERIFICAR",
"proximo_passo": "Definir com Mari / Dr. Kim",
"processo": "5004756-29.2017.4.04.7208",
"parcela": "",
"nf": "",
"situacao_atual": "Roberto Carlos de Souza; inquerito policial; processo BAIXADO 05/09/2025; sem contrato cadastrado; parcela 1/3; VER MARI",
"resolucao_yasmin_kim": "VER MARI",
"alerta": "",
"a_definir": false
},
{
"id": 4296565,
"cliente": "Finger & Cia (Cria Forte)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 8125,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "VERIFICAR",
"proximo_passo": "Conferir documento/valor antes de emitir",
"processo": "extrajudicial / sem processo",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Contrato 2006 prestacao de servicos; varios remanescentes; verificar objeto no GED",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 4432967,
"cliente": "Célio Pacheco",
"tipo": "Êxito",
"via": "Judicial",
"valor": 6403.1,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5013356-73.2016.4.04.7208",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Pacheco Automoveis; exceca pre-executividade, PRESCRICAO INTERCORRENTE reconhecida; cancelou R$64.030,96; 10%=R$6.403,10; MADURO",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 5009544,
"cliente": "Adenis Pasqualetto Júnior",
"tipo": "Êxito",
"via": "Judicial",
"valor": 6091.41,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "0012269-12.2012.8.24.0033",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Acao criminal; R$20.000 corrigido IGPM=R$51.091,41; 'IR cobrando Adenis ate quitar' (cobranca parcial em curso)",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 2195278,
"cliente": "Clauderio Luiz Anton",
"tipo": "Êxito",
"via": "Judicial",
"valor": 4000,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "2397951",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Honor fixo R$4.000 no encerramento da demanda (50% desc se acordo antes sentenca); Shana cobrou 11/2025, consta em aberto",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 4376813,
"cliente": "Marco Aurélio Ambrósio (MG7)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 2751.64,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5003164-08.2021.4.04.7208",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Jose Caetano e Sandra Ambrosio; ANPP; R$25.000 c/ reducao 50% autorizada Dr Kim 11/07/2024; valor remanescente R$2.751,64",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 3005617,
"cliente": "Compass Comércio (Vetor)",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 1000.98,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "4/4",
"nf": "",
"situacao_atual": "Confissao de divida contrato 1579; parte Silva 10%; NF programada no valor cheio na ultima parcela",
"resolucao_yasmin_kim": "CORRETO, PORÉM O VALOR A RECEBER É 250,24",
"alerta": "",
"a_definir": false
},
{
"id": 2454202,
"cliente": "Inoven Comércio Internacional",
"tipo": "Êxito",
"via": "Extrajudicial",
"valor": 195.5,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "extrajudicial / sem processo",
"parcela": "parc 10 acordo",
"nf": "",
"situacao_atual": "Acordo extrajud Inoven x Widerson Santos; parcela 10 R$1.925 x10%",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": false
},
{
"id": 2822919,
"cliente": "Latex Foam do Brasil",
"tipo": "Êxito",
"via": "Judicial",
"valor": 46.65,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5000611-83.2023.8.21.0135",
"parcela": "20/24",
"nf": "",
"situacao_atual": "Latex Foam do Brasil; acordo judicial; honor contratuais R$46,65",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 2822920,
"cliente": "Latex Foam do Brasil",
"tipo": "Êxito",
"via": "Judicial",
"valor": 46.65,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5000611-83.2023.8.21.0135",
"parcela": "21/24",
"nf": "",
"situacao_atual": "Latex Foam; acordo judicial; parcela 21/24",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 2822921,
"cliente": "Latex Foam do Brasil",
"tipo": "Êxito",
"via": "Judicial",
"valor": 46.65,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5000611-83.2023.8.21.0135",
"parcela": "22/24",
"nf": "",
"situacao_atual": "Latex Foam; acordo judicial; parcela 22/24",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 2822922,
"cliente": "Latex Foam do Brasil",
"tipo": "Êxito",
"via": "Judicial",
"valor": 46.65,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5000611-83.2023.8.21.0135",
"parcela": "23/24",
"nf": "",
"situacao_atual": "Latex Foam; acordo judicial; parcela 23/24",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 2822923,
"cliente": "Latex Foam do Brasil",
"tipo": "Êxito",
"via": "Judicial",
"valor": 46.65,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5000611-83.2023.8.21.0135",
"parcela": "24/24",
"nf": "",
"situacao_atual": "Latex Foam; acordo judicial; parcela final 24/24",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 3576617,
"cliente": "Alianca Empreendimentos Imobiliarios (J.A.)",
"tipo": "Sucumbência",
"via": "Judicial",
"valor": 0.1,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "5012332-21.2021.8.24.0005 / cumpr. 5004216-21.2024 / precatorio 5039547-79.2024",
"parcela": "1/1",
"nf": "",
"situacao_atual": "Alianca Empreendimentos; sucumbencia; PRECATORIO AINDA NAO EXPEDIDO; provisionar p/ 01/2026 (precatorio so pago em 2026); NAO COBRAR AINDA",
"resolucao_yasmin_kim": "CORRETO",
"alerta": "",
"a_definir": true
},
{
"id": 3986696,
"cliente": "BBS Binotto Solutions",
"tipo": "Sucumbência",
"via": "Judicial",
"valor": 0.1,
"status_sistema": "Cancelado",
"acao": "EXCLUIR/CANCELAR",
"farol": "EXCLUIR",
"proximo_passo": "Confirmar cancelamento/baixa no sistema",
"processo": "0002703-49.2019.8.24.0500",
"parcela": "",
"nf": "",
"situacao_atual": "CANCELADO (status C). BBS Binotto Solutions x Estado SC; sucumbencia precatoria; valor 0,10",
"resolucao_yasmin_kim": "CANCELADO, ESTAVA DUPLICADO",
"alerta": "",
"a_definir": true
},
{
"id": 4407735,
"cliente": "Marco Aurélio Ambrósio (MG7)",
"tipo": "Sucumbência",
"via": "Judicial",
"valor": 4281.32,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "0500043-49.2011.8.24.0033",
"parcela": "3/3",
"nf": "",
"situacao_atual": "MG7; sucumbencia; AGUARDA EXPEDICAO DE ALVARA (solicitado 25/11/2025); verificar c/ Dr Costella ou Tarcisio",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 4407734,
"cliente": "Marco Aurélio Ambrósio (MG7)",
"tipo": "Sucumbência",
"via": "Judicial",
"valor": 4281.31,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "0500043-49.2011.8.24.0033",
"parcela": "2/3",
"nf": "",
"situacao_atual": "MG7; sucumbencia; AGUARDA EXPEDICAO DE ALVARA (solicitado 25/11/2025); verificar c/ Dr Costella ou Tarcisio",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 3640829,
"cliente": "J. A. Russi",
"tipo": "Êxito",
"via": "Judicial",
"valor": 500,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "5003222-89.2022.8.24.0125",
"parcela": "1/4",
"nf": "",
"situacao_atual": "Russi x Iverts Inthurn Moresco; ATENCAO: acordo homologado 21/08/25 porem PETICIONAMOS DESISTENCIA do acordo p/ prosseguir processo (retorno Dr Thiago); situacao indefinida",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 3640830,
"cliente": "J. A. Russi",
"tipo": "Êxito",
"via": "Judicial",
"valor": 500,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "NAO COBRAR AINDA",
"proximo_passo": "Aguardar evento (decisão/alvará/escritura)",
"processo": "5003222-89.2022.8.24.0125",
"parcela": "2/4",
"nf": "",
"situacao_atual": "Russi x Iverts; parcela 2/4; mesma ressalva: desistencia do acordo peticionada",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 3640831,
"cliente": "J. A. Russi",
"tipo": "Êxito",
"via": "Judicial",
"valor": 500,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5003222-89.2022.8.24.0125",
"parcela": "3/4",
"nf": "",
"situacao_atual": "Russi x Iverts; parcela 3/4; mesma ressalva",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 3640832,
"cliente": "J. A. Russi",
"tipo": "Êxito",
"via": "Judicial",
"valor": 500,
"status_sistema": "Aberto",
"acao": "COBRAR",
"farol": "PRONTO",
"proximo_passo": "Encaminhar para faturamento",
"processo": "5003222-89.2022.8.24.0125",
"parcela": "4/4",
"nf": "",
"situacao_atual": "Russi x Iverts; parcela 4/4; mesma ressalva",
"resolucao_yasmin_kim": "CORRETO, PARCELAS",
"alerta": "",
"a_definir": false
},
{
"id": 2608556,
"cliente": "Brava Beach Empreendimentos",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 300000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "Brava Beach; exito R$300.000 (predio Reserva Recife); Dr Kim 20/03 EXPLICITO: provisionar 150 mil, NAO COBRAR, deixar provisionado",
"resolucao_yasmin_kim": "Dr Kim disse que não saiu, jogar para 2027",
"alerta": "",
"a_definir": false
},
{
"id": 2191810,
"cliente": "Euclides Bragard Belo Junior",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 80000,
"status_sistema": "Aberto",
"acao": "ACAO JUDICIAL",
"farol": "ACAO JUDICIAL",
"proximo_passo": "Acompanhar a ação de cobrança",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "Euclides Bragard; exito via cheque bom p/ 10/12/2024",
"resolucao_yasmin_kim": "AÇÃO JUDICIAL COBRANÇA",
"alerta": "",
"a_definir": false
},
{
"id": 4424836,
"cliente": "KMR Brasil / Heli Brasil Empilhadeiras",
"tipo": "Êxito",
"via": "Judicial",
"valor": 102175.98,
"status_sistema": "Cancelado",
"acao": "EXCLUIR/CANCELAR",
"farol": "EXCLUIR",
"proximo_passo": "Confirmar cancelamento/baixa no sistema",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "CANCELADO (status C). ID incorreto (Dr Kim 28/09): creditos compensados em dez/2025 no id 3565403, ja pago. Revisao PIS/COFINS; 10% de R$1.021.759,77=R$102.175,98",
"resolucao_yasmin_kim": "ID Cancelado, foi verificado que o id está incorreto, em novembro o cliente não utilizou os créditos compensados. Os créditos foram compensados em dez/2025, no id 3565403 e ja foi pago em 10/02/26",
"alerta": "",
"a_definir": false
},
{
"id": 3145095,
"cliente": "Euclides Bragard Belo Junior",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 20000,
"status_sistema": "Aberto",
"acao": "ACAO JUDICIAL",
"farol": "ACAO JUDICIAL",
"proximo_passo": "Acompanhar a ação de cobrança",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "Euclides Bragard; remanescente do id 2191810; exito via cheque",
"resolucao_yasmin_kim": "AÇÃO JUDICIAL COBRANÇA",
"alerta": "",
"a_definir": false
},
{
"id": 2198935,
"cliente": "Guacemmi Participacoes Societarias",
"tipo": "Êxito",
"via": "Judicial",
"valor": 100000,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "5005622-76.2022.8.24.0125",
"parcela": "",
"nf": "",
"situacao_atual": "Guacemmi Participacoes x Joao Pedro Lemos; exito transito em julgado; Dr Kim 28/09: processo NAO encerrado; ver com Kety",
"resolucao_yasmin_kim": "Dr Kim disse que não saiu, jogar para frente",
"alerta": "",
"a_definir": false
},
{
"id": 2194237,
"cliente": "Rodrigo Geremia",
"tipo": "Êxito",
"via": "Judicial",
"valor": 12000,
"status_sistema": "Cancelado",
"acao": "EXCLUIR/CANCELAR",
"farol": "EXCLUIR",
"proximo_passo": "Confirmar cancelamento/baixa no sistema",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "CANCELADO (status C). Acao contra Poti Junior's; Dr Kim 28/09 disse cancelar, indevido",
"resolucao_yasmin_kim": "Dr Kim disse para cancelarmos, indevido",
"alerta": "",
"a_definir": false
},
{
"id": 2197127,
"cliente": "Decio Sanches Madureira",
"tipo": "Êxito",
"via": "A definir (standby)",
"valor": 10000,
"status_sistema": "Cancelado",
"acao": "EXCLUIR/CANCELAR",
"farol": "EXCLUIR",
"proximo_passo": "Confirmar cancelamento/baixa no sistema",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "CANCELADO (status C). Dr Kim 28/09: cliente nao fechou contrato, id indevido",
"resolucao_yasmin_kim": "Dr Kim PASSOU QUE O CLIENTE NÃO FECHOU CONTRATO CONOSCO, ID INDEVIDO.",
"alerta": "",
"a_definir": false
},
{
"id": 3155715,
"cliente": "Romano Distribuidora",
"tipo": "Êxito",
"via": "Judicial",
"valor": 10000,
"status_sistema": "Cancelado",
"acao": "EXCLUIR/CANCELAR",
"farol": "EXCLUIR",
"proximo_passo": "Confirmar cancelamento/baixa no sistema",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "CANCELADO (status C). Honor sucesso liberacao mercadoria R$10.000; Dr Kim 24/01/2025 solicitou nao cobrar; 28/09 cancelar indevido",
"resolucao_yasmin_kim": "Dr Kim disse para cancelarmos, indevido",
"alerta": "",
"a_definir": false
},
{
"id": 4580016,
"cliente": "Heil Malhas (parceria Petruschky/Benedito)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 590644.22,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "Recuperacao Judicial (parceria Petruschky 20%/Benedito); exito classes III+IV; verificar tabela com Dr Daniel",
"resolucao_yasmin_kim": "Dr Kim disse para aguardar, cliente ainda não recebeu crédito",
"alerta": "",
"a_definir": false
},
{
"id": 4546383,
"cliente": "Heil Malhas (parceria Petruschky/Benedito)",
"tipo": "Êxito",
"via": "Judicial",
"valor": 1799364.91,
"status_sistema": "Aberto",
"acao": "AGUARDAR/FRENTE",
"farol": "AGUARDAR",
"proximo_passo": "Aguardar conforme orientação da diretoria",
"processo": "extrajudicial / sem processo",
"parcela": "",
"nf": "",
"situacao_atual": "Recuperacao Judicial (Petruschky/Benedito); reducao global debitos R$11,99mi; exito 15%=R$1.799.364,91; VER com Kim ou Mari p/ cobranca, e-mail GED",
"resolucao_yasmin_kim": "Dr Kim disse para aguardar, cliente ainda não recebeu crédito",
"alerta": "",
"a_definir": false
}
];
const BASE_INFO = {"base": "Receitas vencidas ate 22/09/2026", "geradoEm": "09/10/2026", "fonte": "EasyJur"};
